name: flutter_bloc_test
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  equatable: ^0.6.1
  wave: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true